event-generating flapper plugin for end-to-end testing
blueboxgroup/ursula-monitoring pull request #101
Opened 2016-09-14 21:07 UTC by jyotty

Since upstream monitoring only receives info on state change, we'll use this to constantly generate events as a sort of super-keepalive check.

2016-09-15 17:22 UTC, j2sol commented
This is different than the host keep alive? Is it providing similar functionality?

2016-09-17 01:57 UTC, jyotty commented
@j2sol yes. Keepalive is for sensu client to server; this is for sensu server to the upstream event processor. What we're specifically looking for is if a sensu server stops sending events altogether, or if the upstream aggregator stops processing them, which is a gap in our current monitoring.

2016-09-18 17:33 UTC, omgjlk requested changes
I think this is fine to start with, but it needs to support criticality like the rest of the plugins we've been introducing, unless there is good reason not to.

2016-09-19 19:18 UTC, jyotty commented
Well, there's no threshold for criticality, it's a binary flip between states. I can add an option to make it flip to warning instead of critical though.

2016-09-19 19:34 UTC, j2sol commented
The criticality option is used to turn what would be a critical thing into just a warning. So it doesn't matter if there is a threshold for criticality in the check itself, the criticality option basically neuters the check to prevent pages from unwanted environments.

2016-09-19 19:43 UTC, masteinhauser commented
Criticality still makes sense in the context of this check and the alerting pipeline since notifications differ in critical and warning processing. SiteController will most likely use this check for flipping between `critical` and `ok` as it is currently written, but I could definitely use usage of flipping between `warning` and `ok` also.

tl;dr `-z` / `--criticality` should be supported.

2016-09-19 22:27 UTC, omgjlk approved these changes
All good here now.

2016-09-19 22:38 UTC, merged