Check ceph usage
blueboxgroup/ursula-monitoring pull request #104
Opened 2016-09-20 02:55 UTC by Xiaohua-Shen

to check by pool to support multi-end ceph cluster

2016-09-20 03:17 UTC, j2sol commented on sensu/plugins/check-ceph-usage.rb
> +        critical output
Won't this report only the first pool with a critical level? What if multiple pools are in this state? Wouldn't it be better to report in aggregate, or leave this module as a single pool reporter and create multiple checks, one for each pool?

2016-09-21 00:33 UTC, Xiaohua-Shen commented on sensu/plugins/check-ceph-usage.rb
> +        critical output
all pools usage will be contained in the output, and any of these pools usage meet threshold will be reported as critical.

if both two pools meet critical threshold, output like this:
CheckCephClusterUsage Critical: Pool rbd_hybrid %Used: 81%
Pool rbd_ssd %Used: 76%

if the 2nd pool meet critical threshold, output like this:
CheckCephClusterUsage Critical: Pool rbd_hybrid %Used: 30%
Pool rbd_ssd %Used: 76%

2016-09-21 05:12 UTC, Xiaohua-Shen commented
code is changed, the sample output is like below：
```
root@cpm1:/etc/sensu/plugins# ./check-ceph-usage-new.rb -w 75
CheckCephPoolUsage CRITICAL: rbd_hybrid 76%, rbd_ssd 86%
root@cpm1:/etc/sensu/plugins# ./check-ceph-usage-new.rb -w 80
CheckCephPoolUsage CRITICAL: rbd_ssd 86%
root@cpm1:/etc/sensu/plugins# ./check-ceph-usage-new.rb -w 90
CheckCephPoolUsage OK: All Pools usage under 90%
root@cpm1:/etc/sensu/plugins# ./check-ceph-usage-new.rb -w 75 --criticality warning
CheckCephPoolUsage WARNING: rbd_hybrid 76%, rbd_ssd 86%
```

2016-09-21 18:11 UTC, j2sol commented
Hi @Xiaohua-Shen . Thanks for this, but after some discussion with other consumers of ursula-monitoring, we'd prefer this go in a different direction. We'd rather this plugin grow an argument for which pool to look at (maybe with a reasonable default) so that we can create multiple checks with different configurations that ultimately use the same plugin. The plugin would continue to focus itself on a single pool, either the reasonable default or the specific pool provided to it in an argument.

Does this make sense?

2016-09-21 18:11 UTC, omgjlk requested changes
Please redesign this per comments.

2016-09-22 01:24 UTC, Xiaohua-Shen commented
the pool names are not hardcoded in the check code. it's based on the ```ceph df --format=json``` output, it will contain all the pools existed in this ceph cluster. 
I can add one more optional parameter as pools for the check. if this parameter is provided, then only specific pools will be checked, otherwise all pools will be checked.

2016-09-23 02:40 UTC, knandya commented
@j2sol Does the latest change set look ok?

2016-09-23 17:00 UTC, omgjlk approved these changes

2016-09-23 17:00 UTC, merged