v7k monitoring
blueboxgroup/ursula-monitoring pull request #142
Opened 2017-05-04 11:26 UTC by brianhu2006

add v7k monitoring.
1. add v7k status 
2.add  v7k metrics

2017-05-04 18:42 UTC, knandya commented
Let us mark the PR as WIP while we are figuring out the details.

2017-05-09 05:15 UTC, Xiaohua-Shen requested changes

2017-05-09 05:15 UTC, Xiaohua-Shen commented on sensu/plugins/check_v7k_canister.py
> +    args = parser.parse_args()
Need to add argument of '--criticality'

2017-05-09 05:15 UTC, Xiaohua-Shen commented on sensu/plugins/metrics_v7k.py
> +    args = parser.parse_args()
Need to add argument of '--scheme' to avoid metrics mixture with other envs.

2017-05-11 15:07 UTC, nirajdp76 commented
I think checks need better exception handling. Also, would like to see sample outputs that operators will see when we raise critical alert.

2017-05-11 15:07 UTC, nirajdp76 requested changes
see comment

2017-05-12 13:52 UTC, nirajdp76 approved these changes

2017-05-12 13:52 UTC, merged