Barbican api check
blueboxgroup/ursula-monitoring pull request #143
Opened 2017-05-09 06:43 UTC by wupeiran

Add barbican api check for monitoring

2017-05-09 08:26 UTC, Xiaohua-Shen requested changes

2017-05-09 08:26 UTC, Xiaohua-Shen commented on sensu/plugins/check-os-api.rb
>      end
should omit this 'end'.

2017-05-09 08:32 UTC, wupeiran commented on sensu/plugins/check-os-api.rb
>      end
miss the last end. will update

2017-05-11 15:09 UTC, nirajdp76 commented
We should make the list calls light weight. Goes not all services not just barbican. 
Look at each command help and see what options it provides. --limit 1, etc ..

2017-05-11 15:10 UTC, nirajdp76 requested changes
see comment

2017-05-12 03:29 UTC, wupeiran commented
update commands for list calls light weight

2017-05-12 13:50 UTC, nirajdp76 approved these changes

2017-05-12 13:51 UTC, merged